var cliches = [
  'acid test',
  'at loose ends',
  'babe in the woods',
  'better late than never',
  'brought back to reality',
  'black as pitch',
  'blind as a bat',
  'bolt from the blue',
  'busy as a bee/beaver',
  'cat\'s meow',
  'cool as a cucumber',
  'cool, calm, and collected',
  'crack of dawn',
  'crushing blow',
  'cry over spilt milk',
  'dead as a doornail',
  'dog eat dog world',
  'don\'t count your chickens',
  'dyed in the wool',
  'easier said than done',
  'easy as pie',
  'feathered friends',
  'face the music',
  'flash in the pan',
  'flat as a pancake',
  'gentle as a lamb',
  'go at it tooth and nail',
  'good time was had by all',
  'greased lightning',
  'happy as a lark',
  'head over heels',
  'heavy as lead',
  'horns of a dilemma',
  'hour of need',
  'keep a stiff upper lip',
  'ladder of success',
  'last but not least',
  'looking a gift horse in the mouth ',
  'meaningful dialogue',
  'moving experience',
  'needle in a haystack',
  'open and shut case',
  'pain in the ',
  'point with pride',
  'pretty as a picture',
  'put it in a nutshell',
  'rat race',
  'ripe old age',
  'ruled the roost',
  'sad but true',
  'sadder but wiser',
  'set the world on fire',
  'sick as a dog',
  'sigh of relief',
  'slow as molasses',
  'smart as a whip',
  'sneaking suspicion',
  'spread like wildfire',
  'straight as an arrow',
  'straw that broke the camel\'s back',
  'strong as an ox',
  'take the bull by the horns',
  'thin as a rail',
  'through thick and thin',
  'tired but happy',
  'to coin a phrase',
  'to make a long story short',
  'trial and error',
  'tried and true',
  'under the weather',
  'white as a sheet',
  'wise as an owl',
  'work like a dog',
  'worth its weight in gold'
];

var clicheRegex = new RegExp('\\b(' + cliches.join('|') + ')\\b', 'gi');
var matcher = require("./matcher");

module.exports = function (text) {
  return matcher(clicheRegex, text, "clichés");
};
